/*
 * This file is a part of the ExLibris project.
 *
 * Copyright (C) 2013 Quinten Lansu
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy 
 * of this software and associated documentation files (the "Software"), to deal 
 * in the Software without restriction, including without limitation the rights 
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all 
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
 * SOFTWARE.
 */

#pragma once

namespace ExLibris
{

	enum RtfCountry
	{
		eRtfCountry_None,
		eRtfCountry_Current,
		eRtfCountry_Preferred,
		eRtfCountry_Afghanistan,
		eRtfCountry_Albania,
		eRtfCountry_Algeria,
		eRtfCountry_Argentina,
		eRtfCountry_Armenia,
		eRtfCountry_Australia,
		eRtfCountry_Austria,
		eRtfCountry_Azerbaijan,
		eRtfCountry_Bahrain,
		eRtfCountry_Bangladesh,
		eRtfCountry_Basque,
		eRtfCountry_Belarus,
		eRtfCountry_Belgium,
		eRtfCountry_Belize,
		eRtfCountry_Bolivia,
		eRtfCountry_BosniaAndHerzegovina,
		eRtfCountry_Brazil,
		eRtfCountry_BruneiDarussalam,
		eRtfCountry_Bulgaria,
		eRtfCountry_Cambodia,
		eRtfCountry_Cameroon,
		eRtfCountry_Canada,
		eRtfCountry_Caribbean,
		eRtfCountry_Catalan,
		eRtfCountry_Chile,
		eRtfCountry_ChinaPeoplesRepublicOf,
		eRtfCountry_Colombia,
		eRtfCountry_CongoDemocraticRepublicOf,
		eRtfCountry_CostaRica,
		eRtfCountry_CotedIvoire,
		eRtfCountry_Croatia,
		eRtfCountry_CzechRepublic,
		eRtfCountry_Denmark,
		eRtfCountry_DominicanRepublic,
		eRtfCountry_Ecuador,
		eRtfCountry_Egypt,
		eRtfCountry_ElSalvador,
		eRtfCountry_Estonia,
		eRtfCountry_Ethiopia,
		eRtfCountry_Eritrea,
		eRtfCountry_FaroeIslands,
		eRtfCountry_Finland,
		eRtfCountry_France,
		eRtfCountry_Georgia,
		eRtfCountry_Germany,
		eRtfCountry_Greece,
		eRtfCountry_Greenland,
		eRtfCountry_Guatemala,
		eRtfCountry_Haiti,
		eRtfCountry_Honduras,
		eRtfCountry_Hungary,
		eRtfCountry_Iceland,
		eRtfCountry_India,
		eRtfCountry_Indonesia,
		eRtfCountry_Iraq,
		eRtfCountry_Ireland,
		eRtfCountry_Israel,
		eRtfCountry_Italy,
		eRtfCountry_Jamaica,
		eRtfCountry_Japan,
		eRtfCountry_Jordan,
		eRtfCountry_Kenya,
		eRtfCountry_Korea,
		eRtfCountry_Kuwait,
		eRtfCountry_Kyrgyzstan,
		eRtfCountry_LaoPeoplesDemocraticRepublicOf,
		eRtfCountry_Latvia,
		eRtfCountry_Lebanon,
		eRtfCountry_Libya,
		eRtfCountry_Liechtenstein,
		eRtfCountry_Lithuania,
		eRtfCountry_Luxembourg,
		eRtfCountry_Kazakhstan,
		eRtfCountry_Macedonia,
		eRtfCountry_Malaysia,
		eRtfCountry_Maldives,
		eRtfCountry_Mali,
		eRtfCountry_Malta,
		eRtfCountry_Mexico,
		eRtfCountry_Mohawk,
		eRtfCountry_Moldova,
		eRtfCountry_Monaco,
		eRtfCountry_Mongolia,
		eRtfCountry_Morocco,
		eRtfCountry_Nepal,
		eRtfCountry_Netherlands,
		eRtfCountry_NewZealand,
		eRtfCountry_Nicaragua,
		eRtfCountry_Nigeria,
		eRtfCountry_Norway,
		eRtfCountry_Oman,
		eRtfCountry_Pakistan,
		eRtfCountry_Panama,
		eRtfCountry_Paraguay,
		eRtfCountry_Peru,
		eRtfCountry_Philippines,
		eRtfCountry_Poland,
		eRtfCountry_Portugal,
		eRtfCountry_PuertoRico,
		eRtfCountry_Qatar,
		eRtfCountry_Reunion,
		eRtfCountry_Romania,
		eRtfCountry_Rwanda,
		eRtfCountry_Russia,
		eRtfCountry_SaudiArabia,
		eRtfCountry_Scotland,
		eRtfCountry_Senegal,
		eRtfCountry_Serbia,
		eRtfCountry_Singapore,
		eRtfCountry_Slovakia,
		eRtfCountry_Slovenia,
		eRtfCountry_Spain,
		eRtfCountry_SpecialAdministrativeRegionHongKong,
		eRtfCountry_SpecialAdministrativeRegionMacao,
		eRtfCountry_SriLanka,
		eRtfCountry_SouthAfrica,
		eRtfCountry_Sweden,
		eRtfCountry_Switzerland,
		eRtfCountry_Syria,
		eRtfCountry_Taiwan,
		eRtfCountry_Tajik,
		eRtfCountry_Thailand,
		eRtfCountry_TrinidadAndTobago,
		eRtfCountry_Tunisia,
		eRtfCountry_Turkey,
		eRtfCountry_Turkmenistan,
		eRtfCountry_Ukraine,
		eRtfCountry_UnitedArabicEmirates,
		eRtfCountry_UnitedKingdom,
		eRtfCountry_UnitedStates,
		eRtfCountry_Uruguay,
		eRtfCountry_Uzbekistan,
		eRtfCountry_Venezuela,
		eRtfCountry_Vietnam,
		eRtfCountry_WestIndies,
		eRtfCountry_Yemen,
		eRtfCountry_Zimbabwe,
	};

}; // namespace ExLibris