/*
 * This file is a part of the ExLibris project.
 *
 * Copyright (C) 2013 Quinten Lansu
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy 
 * of this software and associated documentation files (the "Software"), to deal 
 * in the Software without restriction, including without limitation the rights 
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all 
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
 * SOFTWARE.
 */

#pragma once

namespace ExLibris
{

	enum RtfLanguage
	{
		eRtfLanguage_None,
		eRtfLanguage_Custom,
		eRtfLanguage_Afrikaans,
		eRtfLanguage_Albanian,
		eRtfLanguage_Alsatian,
		eRtfLanguage_Amharic,
		eRtfLanguage_Arabic,
		eRtfLanguage_Armenian,
		eRtfLanguage_Assamese,
		eRtfLanguage_AzeriCyrillic,
		eRtfLanguage_AzeriLatin,
		eRtfLanguage_Bashkir,
		eRtfLanguage_Basque,
		eRtfLanguage_Belarusian,
		eRtfLanguage_Bengali,
		eRtfLanguage_BosnianCyrillic,
		eRtfLanguage_BosnianLatin,
		eRtfLanguage_Breton,
		eRtfLanguage_Bulgarian,
		eRtfLanguage_Burmese,
		eRtfLanguage_Catalan,
		eRtfLanguage_Cherokee,
		eRtfLanguage_Chinese,
		eRtfLanguage_Corsican,
		eRtfLanguage_Croatian,
		eRtfLanguage_CroatianLatin,
		eRtfLanguage_Czech,
		eRtfLanguage_Danish,
		eRtfLanguage_Dari,
		eRtfLanguage_Divehi,
		eRtfLanguage_Dutch,
		eRtfLanguage_Dzongkha,
		eRtfLanguage_Edo,
		eRtfLanguage_English,
		eRtfLanguage_Estonian,
		eRtfLanguage_Faroese,
		eRtfLanguage_Filipino,
		eRtfLanguage_Finnish,
		eRtfLanguage_French,
		eRtfLanguage_Frisian,
		eRtfLanguage_Fulfukle,
		eRtfLanguage_Gaelic,
		eRtfLanguage_Georgian,
		eRtfLanguage_German,
		eRtfLanguage_Greek,
		eRtfLanguage_Greenlandic,
		eRtfLanguage_Guarani,
		eRtfLanguage_Gujarati,
		eRtfLanguage_HausaLatin,
		eRtfLanguage_Hawaiian,
		eRtfLanguage_Hebrew,
		eRtfLanguage_Hindi,
		eRtfLanguage_Hungarian,
		eRtfLanguage_Ibibio,
		eRtfLanguage_Icelandic,
		eRtfLanguage_Igbo,
		eRtfLanguage_Indonesian,
		eRtfLanguage_InuktitutLatin,
		eRtfLanguage_InuktitutSyllabics,
		eRtfLanguage_IsiXhosa,
		eRtfLanguage_IsiZulu,
		eRtfLanguage_Italian,
		eRtfLanguage_Japanese,
		eRtfLanguage_Kannada,
		eRtfLanguage_Kanuri,
		eRtfLanguage_KashmiriArabic,
		eRtfLanguage_KashmiriLatin,
		eRtfLanguage_Kazakh,
		eRtfLanguage_Khmer,
		eRtfLanguage_Kiche,
		eRtfLanguage_Kinyarwanda,
		eRtfLanguage_Kiswahili,
		eRtfLanguage_Konkani,
		eRtfLanguage_Korean,
		eRtfLanguage_Kyrgyz,
		eRtfLanguage_Lao,
		eRtfLanguage_Latin,
		eRtfLanguage_Latvian,
		eRtfLanguage_Lithuanian,
		eRtfLanguage_LithuanianTrad,
		eRtfLanguage_LowerSorbian,
		eRtfLanguage_Luxembourgish,
		eRtfLanguage_Macedonian,
		eRtfLanguage_Malay,
		eRtfLanguage_Malayalam,
		eRtfLanguage_Maldivian,
		eRtfLanguage_Maltese,
		eRtfLanguage_Manipuri,
		eRtfLanguage_Maori,
		eRtfLanguage_Mapudungun,
		eRtfLanguage_Marathi,
		eRtfLanguage_Mohawk,
		eRtfLanguage_MonogolianCyrillic,
		eRtfLanguage_MonogolianTraditional,
		eRtfLanguage_Nepali,
		eRtfLanguage_NorwegianBokmal,
		eRtfLanguage_NorwegianNynorsk,
		eRtfLanguage_Occitan,
		eRtfLanguage_Oriya,
		eRtfLanguage_Oromo,
		eRtfLanguage_Papiamentu,
		eRtfLanguage_Pashto,
		eRtfLanguage_Persian,
		eRtfLanguage_Polish,
		eRtfLanguage_Portuguese,
		eRtfLanguage_Punjabi,
		eRtfLanguage_Quechua,
		eRtfLanguage_Romanian,
		eRtfLanguage_Romansh,
		eRtfLanguage_Russian,
		eRtfLanguage_SamiInari,
		eRtfLanguage_SamiLule,
		eRtfLanguage_SamiNorthern,
		eRtfLanguage_SamiSkolt,
		eRtfLanguage_SamiSouthern,
		eRtfLanguage_Sanskrit,
		eRtfLanguage_SerbianCyrillic,
		eRtfLanguage_SerbianLatin,
		eRtfLanguage_SesothoSaLeboa,
		eRtfLanguage_Setswana,
		eRtfLanguage_SindhiArabic,
		eRtfLanguage_SindhiDevanagari,
		eRtfLanguage_Sinhala,
		eRtfLanguage_Slovak,
		eRtfLanguage_Slovenian,
		eRtfLanguage_Somali,
		eRtfLanguage_Spanish,
		eRtfLanguage_SpanishInternational,
		eRtfLanguage_SpanishTraditional,
		eRtfLanguage_Sutu,
		eRtfLanguage_Swedish,
		eRtfLanguage_Syriac,
		eRtfLanguage_TajikCyrillic,
		eRtfLanguage_TamazightArabic,
		eRtfLanguage_TamazightLatin,
		eRtfLanguage_Tamil,
		eRtfLanguage_Tatar,
		eRtfLanguage_Telugu,
		eRtfLanguage_Thai,
		eRtfLanguage_Tibetan,
		eRtfLanguage_Tigrigna,
		eRtfLanguage_Tsonga,
		eRtfLanguage_Turkish,
		eRtfLanguage_Turkmen,
		eRtfLanguage_Uighur,
		eRtfLanguage_Ukrainian,
		eRtfLanguage_UpperSorbian,
		eRtfLanguage_Urdu,
		eRtfLanguage_UzbekCyrillic,
		eRtfLanguage_UzbekLatin,
		eRtfLanguage_Venda,
		eRtfLanguage_Vietnamese,
		eRtfLanguage_Welsh,
		eRtfLanguage_Wolof,
		eRtfLanguage_Xhosa,
		eRtfLanguage_Yakut,
		eRtfLanguage_Yi,
		eRtfLanguage_Yiddish,
		eRtfLanguage_Yoruba,
	};

}; // namespace ExLibris